### PR TITLE
Create FEATURES.md

### PR DESCRIPTION
**Pull request by jakerockland**

### CODE REVIEW

**Comment by jakerockland** [comment]
@lyaunzbe @yoshiwarab I don't think both of you need to review (though would of course be appreciated) but if one of you could PTAL before I submit+send to artists it would be much appreciated.

I wanted to expand on this a bit more, but my day ended up being a bit hectic and want to make sure I get something out rather than nothing to be a clarifying reference for artists, as tomorrow I will have mixed availability traveling in advance of the holiday weekend.

**Review by yoshiwarab — APPROVED** [review]
This looks great, thank you! A couple of things we should add in the future:

1. Note that all code required for calculating features (including additional functions) should be written within the single top level calculate features function.
2. Explanation that the feature fields are required for filtering and rarity to show up on the token page.
3. Info about the two types of feature fields (enum, number). 
    - Enums should be outputted as strings (although I do have extra code to handle if this if that is not the case)
    - Number field step size is used for the step size of the slider in the filters.  
    - If there's only a few numbers expected to be output, the artist might want to use an enum field and output the numbers as strings.
4. Updating features script or features fields will recalculate features for all tokens

**Review by lyaunzbe — APPROVED** [review]

**Comment by jakerockland** [comment]
I added some content here based on your feedback @yoshiwarab, thank you so much for the input. Doing this on tethered cell-phone service, so didn't have the bandwidth to add screenshots at the moment. If I got anything wrong here or should elaborate more in the future, can do so with additional incremental changes. Please feel free to update directly as well or ping me if I am offbase anywhere. 🙏😄

**Comment by jakerockland** [comment]
I added some content here based on your feedback @yoshiwarab, thank you so much for the input. Doing this on tethered cell-phone service, so didn't have the bandwidth to add screenshots at the moment. If I got anything wrong here or should elaborate more in the future, can do so with additional incremental changes. Please feel free to update directly as well or ping me if I am offbase anywhere. 🙏😄

**Pull request merged**
