### PR TITLE
Shared minter suite runbooks

### PR DESCRIPTION
**Pull request by ryley-o**
Update Engine docs with a minter suite migration runbook that explains how to migrate to the new shared minter suite.

Steps are included for:

- steps to migrate from legacy Engine non-shared minter suite to new shared minter suite
- steps to add custom, one-off minters for a single Engine contract to the shared MinterFilter

This PR specifically does not add a runbook tailored to flagship artists for flagship migration. If that communication is desired to be added to the docs site vs. more tailored information being sent in artist communication channels, please highlight this in PR feedback!

This PR states that SDK reference information will be added when it becomes available. It also says that shared randomizer and shared minter filter contract addresses will be as they are deployed to testnets and mainnets.

---

Asana task: https://app.asana.com/0/0/1205139431852181/f

### CODE REVIEW

**Comment by ryley-o** [comment]
Cc @ABDruid - this is all preliminary, and we are not ready for folks to begin migrating to the shared minter suite, but here is an initial cut at a migration runbook 👍 Happy to hear your thoughts and feedback.

**Comment by ryley-o** [comment]
Flipped this back to a draft, because would like to add more details about how engine partners may add custom minters to their contract.

**Comment by ABDruid** [comment]
thanks for keeping me in the loop. Everything looks straight forward and I'll likely lean on eng to help partners configure customized minters for the new architecture.

**Review by jakerockland — APPROVED** [review]

**Comment by ryley-o** [comment]
@jakerockland heads-up that I've generalized this a bit in [3570650](https://github.com/ArtBlocks/artblocks-docs/pull/283/commits/357065053b584cd7ca97c905ee10fc69cb3d9db2) such that I'm comfortable merging this PR before the shared minter suite is released/during migration to the new shared minter suite. 🙏

**Pull request merged**
