### PR TITLE
Adjusting links and added new favicon

### PR DESCRIPTION
**Pull request by geoffreymcgill**

### CODE REVIEW

**Review by jakerockland — APPROVED** [review]
TYVM @geoffreymcgill 🙏 🙏

**Comment by jakerockland** [comment]
@geoffreymcgill do you know, is there a way of readily adding branch preview functionality for Retype with Github actions?

**Comment by jakerockland** [comment]
cc @sarahrossien :)

**Comment by geoffreymcgill** [comment]
> @geoffreymcgill do you know, is there a way of readily adding branch preview functionality for Retype with Github actions?

You should be able to change the following line to the branch you want to build from. 

https://github.com/ArtBlocks/artblocks-docs/blob/main/.github/workflows/retype.yml#L6

I don't think I have previously done that with a PR, so I will need to test quickly to confirm, and see if there are any other ideas from the team.

**Comment by jakerockland** [comment]
> > @geoffreymcgill do you know, is there a way of readily adding branch preview functionality for Retype with Github actions?
> 
> You should be able to change the following line to the branch you want to build from.
> 
> https://github.com/ArtBlocks/artblocks-docs/blob/main/.github/workflows/retype.yml#L6
> 
> I don't think I have previously done that with a PR, so I will need to test quickly to confirm, and see if there are any other ideas from the team.

Ah interesting, will have to see if it is possible to do so programmatically on-the-fly with GH Actions. In any case, not a blocker for this PR, I was just curious :)

Cheers!
Jake

**Pull request merged**
