### PR TITLE
Update faqs.md

### PR DESCRIPTION
**Pull request by madpinney**
FAQ updates!

### CODE REVIEW

**Review by jakerockland — APPROVED** [review]

**Comment by jakerockland** [comment]
@madpinney Could you PTAL at the "resolve conflicts" output and make sure we select the right set of changes branched off of your other #89 that has been merged? https://github.com/ArtBlocks/artblocks-docs/pull/90/conflicts

**Comment by jakerockland** [comment]
@madpinney is this PR still relevant or has it been replaced by other more recent ones?

**Comment by jakerockland** [comment]
Closing this due to stale-ness but we can re-open if I was mistaken here.

**Comment by madpinney** [comment]
Resolved!

**Comment by madpinney** [comment]
Replaced by the latest FAQ request!

**Pull request closed without merging**
